# Generated by Django 4.1.3 on 2022-11-11 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_category_users_comments_article_author_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_tag', models.TextField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='comments',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='likes', to='blog.users'),
        ),
        migrations.AddField(
            model_name='comments',
            name='parent_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='replies', to='blog.comments'),
        ),
        migrations.AlterField(
            model_name='article',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='author', to='blog.users'),
        ),
        migrations.CreateModel(
            name='Subscriptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_notification', models.BooleanField()),
                ('from_who', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='from_who', to='blog.users')),
                ('to_who', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='to_who', to='blog.users')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='blog.article')),
                ('subscriber', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='blog.users')),
            ],
        ),
        migrations.AddField(
            model_name='users',
            name='subscriptions',
            field=models.ManyToManyField(through='blog.Subscriptions', to='blog.users'),
        ),
    ]
